version: "3.9"
services:
  gpsdotnet-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/gpsdotnet-debug:${TAG}
    ports:
      - ${DEBUG_SSH_PORT}:${DEBUG_SSH_PORT}
    devices:
      - "/dev/colibri-uartc:/dev/colibri-uartc"
  gpsdotnet:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/gpsdotnet:${TAG}
    devices:
      - "/dev/colibri-uartc:/dev/colibri-uartc"
